#ifndef ACTIONS_H
#define ACTIONS_H

enum ACTION {
 ACTION_NOTHING=0,
 ACTION_WAIT,
 ACTION_MOVE,
 ACTION_GET,
 ACTION_INVENTORY, /* every operation in inventory takes the same time */
 ACTION_FIRE,
 ACTION_SHOW_HELP,
 ACTION_INC_FIRE,
 ACTION_DEC_FIRE,
 ACTION_OPTIONS,
 ACTION_RELOAD,
 ACTION_SHOW_INFO,
 ACTION_LOOK,
 ACTION_SHOW_VISIBLE,
 ACTION_OPEN,
 ACTION_CLOSE,
 ACTION_THROW,
 ACTION_WAIT_STUNNED,
 ACTION_STAIRS_UP,
 ACTION_STAIRS_DOWN,
 ACTION_REST,
 ACTION_ATTACK,
 ACTION_BUILD_ROBOT,
 ACTION_SHOW_MESSAGE_BUFFER,
 ACTION_ACTIVATE_ARMOR,
 ACTION_ACTIVATE_WEAPON,
 ACTION_SHOUT,
 ACTION_ATTACK_2,
 ACTION_ATTACK_3,
 ACTION_ATTACK_4,
 ACTION_ATTACK_5,	
 ACTION_EXPLORE,
 ACTION_TRAVEL,

 ACTION_SAVE=254,
 ACTION_QUIT=255
};


typedef unsigned long TIME;

#define TIME_LEVEL_CHANGE 0xFFFFFFFF

#define TIME_MOVE 100

#endif

